"use client";

import { useEffect, useRef, useState } from "react";
import { Download, Printer } from "lucide-react";
import type { Session } from "@/lib/luna/auth";
import { impactReport, type Report as ReportData } from "@/lib/luna/impact";
import DonorShell from "@/components/donor/DonorShell";
import { printOnly } from "./print";
import s from "./impact.module.css";

const day = (ms: number) => new Date(ms).toLocaleDateString("en-IN", { day: "numeric", month: "short", year: "numeric" });
const OUTCOME = { delivered: "Delivered", biogas: "Biogas", not_placed: "Not placed", in_progress: "In progress" } as const;

function periods(now: number) {
  const d = new Date(now);
  return [
    { key: "year", label: "This year", from: Date.UTC(d.getUTCFullYear(), 0, 1) - 330 * 60_000, to: now + 1 },
    { key: "90", label: "Last 90 days", from: now - 90 * 86_400_000, to: now + 1 },
    { key: "30", label: "Last 30 days", from: now - 30 * 86_400_000, to: now + 1 },
  ];
}

/**
 * The CSR / ESG impact report (SRS §9): verified meals, kg of food saved and carbon avoided, with how each is
 * counted and the full donation log, ready for a company's report. Says plainly what Luna doesn't claim.
 */
export default function Report({ session }: { session: Session }) {
  const [now] = useState(() => Date.now());
  const options = periods(now);
  const [period, setPeriod] = useState(options[0]);
  const [data, setData] = useState<ReportData | null>(null), [error, setError] = useState("");
  const paper = useRef<HTMLElement>(null);
  useEffect(() => {
    let live = true;
    impactReport(period.from, period.to).then((d) => live && (setData(d), setError("")), (e) => live && setError((e as Error).message));
    return () => { live = false; };
  }, [period, session.token]);

  const csv = () => {
    if (!data) return;
    const rows = [["Date", "Food", "Meals delivered", "NGOs", "Sent to biogas (servings)", "Outcome"], ...data.log.map((e) => [day(e.at), e.food, String(e.delivered), e.ngos.join("; "), String(e.biogas), OUTCOME[e.outcome]])];
    const text = rows.map((r) => r.map((c) => `"${c.replace(/"/g, '""')}"`).join(",")).join("\n");
    const a = document.createElement("a");
    a.href = URL.createObjectURL(new Blob([text], { type: "text/csv" }));
    a.download = `luna-donation-log-${data.name.toLowerCase().replace(/[^a-z0-9]+/g, "-")}.csv`;
    a.click();
  };

  return (
    <DonorShell title="CSR / ESG report" back={{ label: "Your impact", href: "/impact" }}>
      <div className={s.page}>
        <div className={s.chips} role="radiogroup" aria-label="Period">
          {options.map((p) => <button key={p.key} type="button" role="radio" aria-checked={period.key === p.key} className={s.chip} data-on={period.key === p.key} onClick={() => setPeriod(p)}>{p.label}</button>)}
        </div>
        {error && <p className={s.error} role="alert">{error}</p>}
        {!data ? <p className={s.note}>Preparing your report…</p> : (
          <>
            <article className={s.report} ref={paper} aria-labelledby="report-title">
              <header>
                <h1 id="report-title">Food donation impact report</h1>
                <p className={s.note}>{data.name}{data.area ? `, ${data.area}` : ""} · {day(data.from)} to {day(Math.min(data.to, data.generatedAt))}{data.fssai ? ` · FSSAI ${data.fssai}` : ""}</p>
                <p className={s.note}>Generated by Luna on {day(data.generatedAt)}{data.partnerSince ? ` · Luna Partner since ${day(data.partnerSince)}` : ""}</p>
              </header>
              <section className={s.figures} aria-label="Summary">
                <div><b>{data.meals}</b><span>Meals delivered</span></div>
                <div><b>{data.deliveries}</b><span>Deliveries</span></div>
                <div><b>{data.ngos}</b><span>NGOs reached</span></div>
                <div><b>~{data.kgSaved}</b><span>kg food saved (est.)</span></div>
                <div><b>~{data.co2eKg}</b><span>kg CO₂e avoided (est.)</span></div>
                <div><b>{data.biogasServings}</b><span>Servings to biogas</span></div>
              </section>
              <section>
                <h2>How these are counted</h2>
                <div className={s.fine}>
                  <p><b>Meals</b> are servings that reached an NGO, each delivery confirmed with a drop code at handover. Food that was listed but not delivered is not counted.</p>
                  <p><b>kg of food</b> uses the restaurant&rsquo;s own weight where it listed in kg, otherwise {Math.round(data.method.kgPerServing * 1000)} g per meal (Luna&rsquo;s estimate). <b>CO₂e</b> uses {data.method.co2ePerKg} kg per kg of food not wasted (FAO, <i>Food Wastage Footprint</i>, 2013).</p>
                  <p>Food donations don&rsquo;t qualify for a tax deduction under Section 80G, which covers money only. Whether these figures can go in a CSR filing is for your chartered accountant to confirm.</p>
                </div>
              </section>
              <section>
                <h2>Donation log</h2>
                <div className={s.tableWrap}>
                  <table className={s.table}>
                    <thead><tr><th>Date</th><th>Food</th><th>Meals</th><th>NGOs</th><th>Biogas</th><th>Outcome</th></tr></thead>
                    <tbody>
                      {data.log.length === 0 && <tr><td colSpan={6}>No donations in this period.</td></tr>}
                      {data.log.map((e) => <tr key={e.listingId}><td>{day(e.at)}</td><td>{e.food}</td><td>{e.delivered}</td><td>{e.ngos.join(", ") || "—"}</td><td>{e.biogas || "—"}</td><td>{OUTCOME[e.outcome]}</td></tr>)}
                    </tbody>
                  </table>
                </div>
              </section>
            </article>
            <div className={s.chips}>
              <button type="button" className={s.printButton} onClick={() => printOnly(paper.current)}><Printer size={18} aria-hidden /> Print or save as PDF</button>
              <button type="button" className={s.outlineButton} onClick={csv}><Download size={18} aria-hidden /> Donation log (CSV)</button>
            </div>
          </>
        )}
      </div>
    </DonorShell>
  );
}
